# Recommended configuration enabling Web UI access behind Ingress
deployment:
  replicaCount: 3

garage:
  replicationFactor: "2"
  secret:
    rpcSecret: "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1" # openssl rand -hex 32
    adminToken: "V9mT2xKpQw5rLjNzYuBvCdFgHiJkMnOwPqRsT1uVwX2yZaBc" # openssl rand -base64 32
  s3:
    api:
      rootDomain: ".s3.garage.example.com"
    web:
      rootDomain: ".web.garage.example.com"

persistence:
  enabled: true
  data:
    storageClass: garage-data-hdd
    size: 10Gi
  meta:
    storageClass: garage-meta-ssd
    size: 500Mi

clusterConfig:
  enabled: true
  layout:
    enabled: true
    zone: dc1
  buckets:
    - name: media
      public: true
    - name: backups
    - name: staging
  keys:
    recommended-key:
      keyId: GK89ABCDEF0123456789ABCDEF
      secretKey: fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210
      buckets:
        - media
        - backups
        - staging

ingress:
  s3:
    api:
      enabled: true
      className: nginx
      hosts:
        - host: s3.garage.example.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: s3-garage-tls
          hosts:
            - s3.garage.example.com
    web:
      enabled: true
      className: nginx
      hosts:
        - host: web.garage.example.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: web-garage-tls
          hosts:
            - web.garage.example.com

webui:
  enabled: true

  auth:
    enabled: true
    userPassHash: "admin:$2y$10$wjnUPtyPiODuT7f1t5rs5O.HYYpM0EeP0D7EXoeHKfBwPX7rUSaTG" # htpasswd -nbBC 10 "admin" "admin1234"

  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: garage-ui.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: garage-ui-tls
        hosts:
          - garage-ui.example.com
