{{- if .Values.ingress.enabled }}
{{- $defaultHost := printf "%s.qa.az1.kilroy.eu" (include "openvasd-parent.serviceName" .) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" .Release.Name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "openvasd-parent.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - {{- if .host }}
      host: {{ .host | quote }}
      {{- else }}
      host: {{ $defaultHost | quote }}
      {{- end }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "openvasd-parent.serviceName" $ }}
                port:
                  number: {{ $.Values.openvasd.service.port }}
          {{- end }}
    {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- range . }}
    - secretName: {{ .secretName }}
      hosts:
        {{- if .hosts }}
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
        {{- else }}
        - {{ $defaultHost | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
