config:
  MD013:
    line_length: 120
    code_blocks: false
    tables: false

  MD034: false

ignores:
  - 'argocd-helm-charts/*/*/**'
  - 'argocd-helm-charts/*/*.md'
  - 'CHANGELOG.md'
  - 'build/vendor/**'
  - 'build/kube-prometheus/**'
  - 'build/opendesk/**'
