calcom:
  replicaCount: 1

  image:
    repository: calcom/cal.com
    pullPolicy: IfNotPresent
    tag: v5.0.19

  imagePullSecrets: []

  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  secretRef: "calcom"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - host: calcom.example.org
        paths:
          - path: /
            pathType: Prefix
    tls: []

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

postgresql:
  enabled: true
  monitoring:
    enablePodMonitor: true
  instance: 1
  size: 10Gi
  recover: false
  bootstrap:
    initdb:
      database: calcom
      owner: calcom
  resources:
    limits:
      memory: 800Mi
      cpu: 500m
    requests:
      memory: 500Mi
      cpu: 100m
