apiVersion: v2
appVersion: v16.10.1
dependencies:
- alias: mariadb-subchart
  condition: mariadb.enabled,mariadb-subchart.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 11.5.7
- alias: postgresql-subchart
  condition: postgresql.enabled,postgresql-subchart.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.1.6
- alias: redis-cache
  condition: redis-cache.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.15.2
- alias: redis-queue
  condition: redis-queue.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.15.2
- alias: dragonfly-cache
  condition: dragonfly-cache.enabled
  name: dragonfly
  repository: oci://ghcr.io/dragonflydb/dragonfly/helm
  version: v1.34.2
- alias: dragonfly-queue
  condition: dragonfly-queue.enabled
  name: dragonfly
  repository: oci://ghcr.io/dragonflydb/dragonfly/helm
  version: v1.34.2
- alias: valkey-cache
  condition: valkey-cache.enabled
  name: valkey
  repository: https://valkey-io.github.io/valkey-helm
  version: 0.9.3
- alias: valkey-queue
  condition: valkey-queue.enabled
  name: valkey
  repository: https://valkey-io.github.io/valkey-helm
  version: 0.9.3
description: Kubernetes Helm Chart for the latest stable ERPNext branch
icon: https://raw.githubusercontent.com/frappe/erpnext/develop/erpnext/public/images/erpnext-logo.png
name: erpnext
type: application
version: 8.0.36
