hcloud-cloud-controller-manager:
  env:
    HCLOUD_TOKEN:
      valueFrom:
        secretKeyRef:
          name: cloud-credentials
          key: hcloud

    ROBOT_USER:
      valueFrom:
        secretKeyRef:
          name: cloud-credentials
    ROBOT_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: cloud-credentials

  networking:
    network:
      valueFrom:
        secretKeyRef:
          name: cloud-credentials

  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
