name: promtool

"on":
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  promtool:
    name: Prometheus rule test
    runs-on: ubuntu-latest
    container:
      image: ${{ secrets.HARBOR_REGISTRY }}/${{ vars.KUBEAID_CI_IMAGE }}:1.2.0
      credentials:
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: promtool
        working-directory: argocd-helm-charts/prometheus-linuxaid/tests
        run: promtool test rules *.yaml

      - name: prometheus mixins rules check and lint
        working-directory: build/kube-prometheus/mixins
        run: |
          set -e
            for dir in */; do
              if [ -f "${dir}prometheus.yaml" ] && [ -f "${dir}mixin.libsonnet" ]; then
                promtool check rules "${dir}prometheus.yaml"
                mixtool lint --prometheus "${dir}mixin.libsonnet"
              else
                echo "Did not find either 'mixin.libsonnet' or 'prometheus.yaml' in '$dir'"
                exit 1
              fi
            done

      - name: jsonnet unit tests
        working-directory: build/kube-prometheus
        run: |
          bash tests/lint_vars_access.sh
          for version in libraries/*/; do
            echo "Testing against ${version}vendor"
            jsonnet -J "${version}vendor" tests/addmixin_test.jsonnet
            jsonnet -J "${version}vendor" tests/validate_vars_test.jsonnet
          done

      - name: kube-prometheus e2e compilation tests
        working-directory: build/kube-prometheus
        run: bash e2e/run.sh
