{{- $postgresql := .Values.postgresql }}

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-pgsql

spec:
  instances: {{ $postgresql.instances }}

  {{- with $postgresql.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  storage:
    size: {{ $postgresql.size }}
    {{- if $postgresql.storageClass }}
    storageClass: {{ $postgresql.storageClass }}
    {{- end }}

  {{- if $postgresql.backups.enabled }}
  plugins:
    - enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: keycloak-pgsql-backups
        serverName: "revision-{{ $postgresql.revision }}"
  {{- end }}

  bootstrap:
    {{- if $postgresql.recover.enabled }}
    recovery: keycloak-pgsql
    {{- else }}
    initdb:
      database: keycloak
      owner: keycloak
    {{- end }}

  {{- if $postgresql.recover.enabled }}
  externalClusters:
    - name: keycloak-pgsql
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: keycloak-pgsql-backups
          serverName: "revision-{{ $postgresql.recover.revision }}"
  {{- end }}
