{{- if .Values.garage.secret.create }}
{{- include "garage.secret.validate" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garage.secretName" . }}
  {{- if eq (include "garage.secret.hasRandomSecrets" .) "true" }}
  annotations:
    "helm.sh/resource-policy": keep
    "argocd.argoproj.io/compare-options": IgnoreExtraneous
  {{- end }}
  labels:
    {{- include "garage.labels" . | nindent 4 }}
type: Opaque
data:
{{ include "garage.secret.content" . | indent 2 }}
{{- else }}
  {{- if and ((and (.Values.webui.enabled) (.Values.webui.auth.enabled))) (not .Values.webui.auth.existingSecret) }}
  {{- fail "webui.auth.existingSecret is required when garage.secret.create is false and webui.auth.enabled is true" }}
  {{- end }}
{{- end }}
