{{- if .Values.externalDatabases.netbird.monitoring.enablePodMonitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ if .Values.externalDatabases.netbird.recover }}netbird-pgsql-recover{{ else }}netbird-pgsql{{ end }}
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      cnpg.io/cluster: "{{ if .Values.externalDatabases.netbird.recover }}netbird-pgsql-recover{{ else }}netbird-pgsql{{ end }}"
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 10s
      scrapeTimeout: 10s
{{- end }}