{{- if .Values.oval.enabled }}
{{- $oval := .Values.oval.fetchDB -}}
{{- range $distro, $versions := $oval -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "vuls-dictionary.fullname" $ }}-oval-{{ $distro }}-fetch-jobs
spec:
  suspend: false
  schedule: {{ $.Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: dictionary
              persistentVolumeClaim:
                claimName: {{ include "vuls-dictionary.fullname" $ }}-pvc
          restartPolicy: OnFailure
          containers:
            - name: {{ include "vuls-dictionary.fullname" $ }}-oval-{{ $distro }}
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 16 }}
              image: "{{ $.Values.image.oval.repository }}:{{ $.Values.image.oval.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command:
                - goval-dictionary
                - fetch
                {{- if eq $distro "sles-server" }}
                - suse
                - --suse-type
                - suse-enterprise-server
                {{- else }}
                - {{ $distro }}
                {{- end }}
                {{- range $version := $versions }}
                - {{ $version | quote }}
                {{- end }}
              resources:
                {{- toYaml $.Values.resources | nindent 16 }}
              volumeMounts:
                - name: dictionary
                  mountPath: /go-cve-dictionary
---
{{- end }}
{{- end }}
