{{- if .Values.cve.enabled }}
{{- $dictionaries := .Values.cve.fetchDB -}}
{{- $pgHost := printf "%s-pgsql-rw" (include "vuls-dictionary.fullname" .) -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "vuls-dictionary.fullname" . }}-cve-fetch-jobs
spec:
  suspend: false
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            {{- range $index, $dict := $dictionaries }}
            - name: {{ include "vuls-dictionary.fullname" $ }}-cve-{{ $dict }}
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 16 }}
              image: "{{ $.Values.image.cve.repository }}:{{ $.Values.image.cve.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command:
                - go-cve-dictionary
                - fetch
                - {{ $dict }}
                - --dbtype
                - postgres
                - --dbpath
                - $(DB_PATH)
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "vuls-dictionary.fullname" $ }}-pgsql-app
                      key: password
                - name: DB_PATH
                  value: "host={{ $pgHost }} port=5432 user=vuls dbname=vuls password=$(DB_PASSWORD) sslmode=require"
              resources:
                {{- toYaml ($.Values.cve.resources | default $.Values.resources) | nindent 16 }}
            {{- end }}
{{- end }}
