{{- $postgresql := .Values.postgresql }}
{{- $fullname := include "vuls-dictionary.fullname" . }}

{{- $clusters := list }}
{{- if .Values.cve.enabled }}
{{-   $clusters = append $clusters (dict "name" "cve" "database" "vuls" "owner" "vuls") }}
{{- end }}

{{- range $i, $cluster := $clusters }}
{{- if $i }}
---
{{- end }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ $fullname }}-pgsql-{{ $cluster.name }}

spec:
  instances: {{ $postgresql.instances }}

  {{- with $postgresql.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  storage:
    size: {{ $postgresql.size }}
    {{- if $postgresql.storageClass }}
    storageClass: {{ $postgresql.storageClass }}
    {{- end }}

  {{- if $postgresql.backups.enabled }}
  plugins:
    - enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: {{ $fullname }}-pgsql-{{ $cluster.name }}-backups
        serverName: "revision-{{ $postgresql.revision }}"
  {{- end }}

  bootstrap:
    {{- if $postgresql.recover.enabled }}
    recovery: {{ $fullname }}-pgsql-{{ $cluster.name }}
    {{- else }}
    initdb:
      database: {{ $cluster.database }}
      owner: {{ $cluster.owner }}
    {{- end }}

  {{- if $postgresql.recover.enabled }}
  externalClusters:
    - name: {{ $fullname }}-pgsql-{{ $cluster.name }}
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: {{ $fullname }}-pgsql-{{ $cluster.name }}-backups
          serverName: "revision-{{ $postgresql.recover.revision }}"
  {{- end }}

  monitoring:
    enablePodMonitor: {{ if hasKey (default dict $postgresql.monitoring) "enablePodMonitor" }}{{ $postgresql.monitoring.enablePodMonitor }}{{ else }}{{ $postgresql.backups.enabled }}{{ end }}
    {{- $monitoringExtra := omit (default dict $postgresql.monitoring) "enablePodMonitor" }}
    {{- if $monitoringExtra }}
    {{- $monitoringExtra | toYaml | nindent 4 }}
    {{- end }}
{{- end }}
