{{- if .Values.vulsServer.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "vuls-dictionary.fullname" . }}-results-pvc
  labels:
    {{- include "vuls-dictionary.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.vulsServer.resultsStorage.accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ .Values.vulsServer.resultsStorage.size | default "2Gi" }}
{{- if .Values.vulsServer.resultsStorage.storageClass }}
  storageClassName: "{{ .Values.vulsServer.resultsStorage.storageClass }}"
{{- end }}
{{- end }}
