{{- if and .Values.gfetch.enabled .Values.gfetch.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "puppetserver.name" . }}-gfetch
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: gfetch
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http-metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/component: gfetch
{{- end }}
