{{- if (.Values.mariadb.logicalbackup).enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-logical-backup
spec:
  concurrencyPolicy: Forbid
  suspend: false
  schedule: {{ (.Values.mariadb.logicalbackup).schedule | default "30 00 * * *" | quote }}
  successfulJobsHistoryLimit: {{ (.Values.mariadb.logicalbackup).successfulJobsHistoryLimit | default 3 }}
  failedJobsHistoryLimit: {{ (.Values.mariadb.logicalbackup).failedJobsHistoryLimit | default 1 }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: logical-backup
              image: ghcr.io/obmondo/mariadb-logical-backup:3.1.8
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  memory: 500Mi
              env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: MARIADB_HOST
                  value: {{ .Values.mariadb.host | default "matomo-mariadb" | quote }}
                - name: MARIADB_PORT
                  value: {{ .Values.mariadb.port | default 3306 | quote }}
                - name: MARIADB_USER
                  value: {{ .Values.mariadb.username | default "matomo" | quote }}
                - name: MARIADB_DATABASE
                  value: {{ .Values.mariadb.database | default "matomo" | quote }}
                - name: MARIADB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mariadb-secret
                      key: db-password
                - name: CLUSTER_NAME_LABEL
                  value: {{ (.Values.mariadb.logicalbackup).pgOperatorClusterName | default "matomo-mariadb" | quote }}
            {{- if eq (.Values.mariadb.logicalbackup).provider "s3" }}
                - name: LOGICAL_BACKUP_PROVIDER
                  value: "s3"
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ (.Values.mariadb.logicalbackup).secretName | default "matomo-mariadb-pod-env" | quote }}
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ (.Values.mariadb.logicalbackup).secretName | default "matomo-mariadb-pod-env" | quote }}
                      key: AWS_SECRET_ACCESS_KEY
                - name: LOGICAL_BACKUP_S3_ENDPOINT
                  value: {{ (.Values.mariadb.logicalbackup).s3endpoint | quote }}
                - name: LOGICAL_BACKUP_S3_BUCKET
                  value: {{ (.Values.mariadb.logicalbackup).s3bucket | quote }}
                - name: LOGICAL_BACKUP_S3_BUCKET_SCOPE_SUFFIX
                  value: {{ (.Values.mariadb.logicalbackup).s3bucketscopesuffix | default "logicalbackup" | quote }}
                - name: LOGICAL_BACKUP_S3_REGION
                  value: {{ (.Values.mariadb.logicalbackup).s3region | default "us-east-1" | quote }}
                - name: LOGICAL_BACKUP_S3_RETENTION_TIME
                  value: {{ (.Values.mariadb.logicalbackup).retention | default "30 days" | quote }}

              {{- else if eq .Values.mariadb.logicalbackup.provider "az" }}
                - name: LOGICAL_BACKUP_PROVIDER
                  value: "az"
                - name: LOGICAL_BACKUP_AZURE_STORAGE_ACCOUNT_NAME
                  value: {{ (.Values.mariadb.logicalbackup).storeageaccount }}
                - name: LOGICAL_BACKUP_AZURE_STORAGE_CONTAINER
                  value: {{ (.Values.mariadb.logicalbackup).azurecontainer }}
                - name: LOGICAL_BACKUP_AZURE_STORAGE_ACCOUNT_KEY
                  valueFrom:
                    secretKeyRef:
                      key: LOGICAL_BACKUP_AZURE_STORAGE_ACCOUNT_KEY
                      name: matomo-mariadb-pod-env
                - name: LOGICAL_BACKUP_S3_BUCKET
                  value: {{ (.Values.mariadb.logicalbackup).azurecontainer }}
                - name: LOGICAL_BACKUP_S3_BUCKET_SCOPE_SUFFIX
                  value: {{ (.Values.mariadb.logicalbackup).s3bucketscopesuffix | default "logicalbackup" }}

            {{- end }}
              securityContext:
                allowPrivilegeEscalation: true
                privileged: false
                readOnlyRootFilesystem: false
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          terminationGracePeriodSeconds: 300
{{- end }}