oncall:
  # Install the grafana-oncall-app plugin from local image registry via an init container.
  # Enable this when running in an air-gapped environment.
  grafanaPluginInstall:
    enabled: false
  oncall:
    telegram:
      enabled: true
      token: ~
      webhookUrl: ~
  engine:
    replicaCount: 1
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 600m
        memory: 1Gi
  celery:
    replicaCount: 1
    resources:
      limits:
        cpu: 300m
        memory: 750Mi
      requests:
        cpu: 300m
        memory: 750Mi
  ingress-nginx:
    enabled: false
  cert-manager:
    enabled: false
  database:
    type: postgresql
  mariadb:
    enabled: false
  postgresql:
    enabled: false
  redis:
    enabled: true
    auth:
      enabled: true
      existingSecret: oncall-redis
      existingSecretPasswordKey: redis-password
  rabbitmq:
    enabled: false
  grafana:
    enabled: true
    persistence:
      size: 1Gi
    grafana.ini:
      analytics:
        check_for_updates: true
  externalPostgresql:
    host: oncall-pgsql-rw
    port: 5432
    db_name: oncall
    user: oncall
    existingSecret: oncall-pgsql-app
    passwordKey: password
  externalRabbitmq:
    host: oncall-rabbitmq
    port: 5672
    vhost: '/'
    existingSecret: oncall-rabbitmq-default-user
    passwordKey: password
    usernameKey: username
  ingress:
    enabled: true
  uwsgi: null

global:
  netpol:
    enabled: false
  
  celery:
    netpol: false

  engine:
    netpol: false

  redis:
    netpol: false
    enabled: true

  grafana:
    netpol: false

  postgresql:
    enabled: true
    recover: false
    instance: 2
    instanceName: oncall-pgsql
    netpol: false
    clients:
      - labels:
          app.kubernetes.io/instance: oncall
          app.kubernetes.io/component: engine
      - labels:
          app.kubernetes.io/instance: oncall
          app.kubernetes.io/component: celery
    cnpg:
      labels:
        app.kubernetes.io/name: cloudnative-pg
        io.kubernetes.pod.namespace: cloudnative-pg
    size: 2Gi
    logicalBackup: true
    resources:
      limits:
        memory: 800Mi
      requests:
        memory: 500Mi
        cpu: 100m
    backup:
      enabled: true
      cloud: aws
      destinationPath: s3://oncall-backups
      endpointURL: https://s3.abc.com
      secretName: oncall-psql-backup-creds
      azureCredentials:
        connectionString:
          key: AZURE_CONNECTION_STRING
        storageAccount:
          key: AZURE_STORAGE_ACCOUNT
        storageKey:
          key: AZURE_STORAGE_KEY
        storageSasToken:
          key: AZURE_STORAGE_SAS_TOKEN

  rabbitmq:
    enabled: true
    netpol: true
    replicas: 1
    additionalConfig:
      vm_memory_high_watermark_paging_ratio: 0.99
    resources:
      limits:
        cpu: 100m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 2Gi
    image:
      repository: bitnamilegacy/rabbitmq
      tag: 3.12.0-debian-11-r0
