{{- if .Values.cnpg.enabled }}
{{- $cnpg := .Values.cnpg }}

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sonarqube-pgsql
  {{- with $cnpg.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    velero.io/exclude-from-backup: "true"

spec:
  instances: {{ $cnpg.instances }}

  # This needs to be tied to the specific version of sonarqube
  # Currently, this pgsql v17 supports till Sonarqube v26.1.0-community
  # Newer versions of Sonarqube can use pgsql v18 and above.
  # NOTE: If the imageName is not specified, then the cnpg-operator will spin up latest pgsql
  # depending on operator version which can be incompatible with Sonarqube version.

  imageName: ghcr.io/cloudnative-pg/postgresql:17-system-trixie

  {{- with $cnpg.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  storage:
    size: {{ $cnpg.size }}
    {{- if $cnpg.storageClass }}
    storageClass: {{ $cnpg.storageClass }}
    {{- end }}

  {{- if $cnpg.backups.enabled }}
  plugins:
    - enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: sonarqube-pgsql-backups
        serverName: "revision-{{ $cnpg.revision }}"
  {{- end }}

  bootstrap:
    {{- if $cnpg.recover.enabled }}
    recovery: sonarqube-pgsql
    {{- else }}
    initdb:
      database: sonarqube
      owner: sonarqube
    {{- end }}

  {{- if $cnpg.recover.enabled }}
  externalClusters:
    - name: sonarqube-pgsql
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: sonarqube-pgsql-backups
          serverName: "revision-{{ $cnpg.recover.revision }}"
  {{- end }}

  monitoring:
    enablePodMonitor: {{ if hasKey (default dict $cnpg.monitoring) "enablePodMonitor" }}{{ $cnpg.monitoring.enablePodMonitor }}{{ else }}{{ $cnpg.backups.enabled }}{{ end }}
    {{- $monitoringExtra := omit (default dict $cnpg.monitoring) "enablePodMonitor" }}
    {{- if $monitoringExtra }}
    {{- $monitoringExtra | toYaml | nindent 4 }}
    {{- end }}
{{- end }}
