{{- if and ((.Values.global).netpol).enabled ((.Values.global).postgresql).netpol }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.global.postgresql.instanceName | default "postgresql" }}-networkpolicy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: cilium-networkpolicy
spec:
  endpointSelector:
    matchLabels:
      cnpg.io/cluster: {{ .Values.global.postgresql.instanceName | default "postgresql" }}

# =========
# EGRESS
# =========

  egress:
    # Allow egress to kube-apiserver
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "6443"
              protocol: TCP

    # Communication between postgres pods
    - toEndpoints:
        - matchLabels:
            cnpg.io/cluster: {{ .Values.global.postgresql.instanceName | default "postgresql" }}
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
            - port: "8000"
              protocol: TCP

# ========
# INGRESS
# ========

  ingress:
    {{- if .Values.global.postgresql.clients }}
    # allow ingress from client applications
    {{- range .Values.global.postgresql.clients }}
    - fromEndpoints:
        - matchLabels:
            {{- range $key, $value := .labels }}
            {{ $key }}: {{ $value }}
            {{- end }}
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
    {{- end }}
    {{- end }}

    {{- if .Values.global.postgresql.cnpg }}
    # allow ingress from CNPG operator
    - fromEndpoints:
        - matchLabels:
            {{- range $key, $value := .Values.global.postgresql.cnpg.labels }}
            {{ $key }}: {{ $value }}
            {{- end }}
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
    {{- end }}

    # communication between postgres pods
    - fromEndpoints:
        - matchLabels:
            cnpg.io/cluster: {{ .Values.global.postgresql.instanceName | default "postgresql" }}
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
            - port: "8000"
              protocol: TCP

{{- end }}
