{{- if and ((.Values.global).netpol).enabled ((.Values.global).whoami).netpol }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.global.netpol.releaseName }}-whoami-networkpolicy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: cilium-networkpolicy
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: whoami
      app.kubernetes.io/instance: {{ .Values.global.netpol.releaseName }}

# ========
# INGRESS
# ========

  ingress:
    # Allow traffic only from Traefik ingress controller to the whoami HTTP port
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: {{ .Values.global.netpol.traefik.namespace }}
            {{- range $key, $value := .Values.global.netpol.traefik.labels }}
            {{ $key }}: {{ $value }}
            {{- end }}
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
{{- end }}
